"""Autogenerated solution template, v2"""
__version__ = 2

from typing import List, Any, Tuple
from framework.helpers import solution_timer
from framework.input_helper import read_entire_input

from collections import Counter

data = read_entire_input(2024,1)
test = """3   4
4   3
2   5
1   3
3   9
3   3""".split("\n")

def parse(data: List[str]) -> Tuple[List[int], List[int]]:
    list1 = []
    list2 = []
    for row in data:
        i = row.find(" ")
        a,b = int(row[:i]), int(row[i:])
        list1.append(a)
        list2.append(b)
    return list1, list2

# @solution_timer(2024,1,1)
def part_one(data: List[str], verbose=False):
    list1, list2 = parse(data)
    list1 = sorted(list1)
    list2 = sorted(list2)
    tot = 0
    for a,b in zip(list1, list2):
        tot += abs(a-b)
    return tot

# @solution_timer(2024,1,2)
def part_two(data: List[str], verbose=False):
    list1, list2 = parse(data)
    c = Counter(list2)
    tot = 0
    for a in list1:
        tot += a * c[a]

    return tot

if __name__ == "__main__":
    data = read_entire_input(2024,1)
    part_one(data)
    part_two(data)