"""Autogenerated solution template, v2"""
__version__ = 2

from typing import List, Any, Tuple
from framework.input_helper import read_entire_input

YEAR = 2022
DAY = 24
VERSION = "None"

data = read_entire_input(2022,24)
test = """""".split("\n")

def parse(data: List[str]) -> Any:
    return data

def part_one(data: List[str], verbose=False):
    _ = parse(data)

    return False

def part_two(data: List[str], verbose=False):
    _ = parse(data)

    return False

if __name__ == "__main__":
    data = read_entire_input(YEAR, DAY)
    part_one(data)
    part_two(data)